@startuml

class Airport{
    name;
}
class City{
    name;
    airports;
}

class AirPlane{
    capacity;
    description;
}

class Airline{
    flights;
}
class Flight{
    passengers;
    airCrews;
    plane;
    departDateTime;
    departure;
    destination;
}

class Passenger{
    name;
    surname;
}

class AirCrew{
    type;
    name;
    surname;
    airline;
}
class flightPath{
    flights;
    layovers;
}
class Layover{
    airport;
    durationAproxInMin;
}

Flight -> Airport
Flight -> Passenger: *
Flight -> AirCrew: *
Flight -> AirPlane
Airline -> Flight: *
AirCrew -> Airline
flightPath -> Flight: *
flightPath -> Layover: *
City -> Airport: *

@enduml