@startuml

class Airport{
    name;
}
class City{
    name;
    airports;
}

class AirPlane{
    capacity;
    description;
}

class Airline{
    flights;
}
class Flight{
    passengers;
    airCrews;
    plane;
    departure;
    destination;
}

class Passenger{
    name;
    surname;
}

class AirCrew{
    type;
    name;
    surname;
}

class Layover{
    airport;
    durationAproxInMin;
}
City -> Airport: *
Flight -> Airport
Flight -> Passenger: *
Flight -> AirCrew: *
Fligth -> AirPlane
Airline -> Flight: *
AirCrew -> Airline


@enduml